---
name: "Setup Dagger"
description: "Setup Dagger"
inputs:
  version:
    description: |
      "Dagger version to install"
    default: "0.9.5"
  cloudToken:
    description: |
      "Dagger cloud token"
    required: true
  cacheServiceURL:
    description: |
      "Dagger cache service URL"
    default: "https://api.dagger.cloud/magicache"
  cacheServiceToken:
    description: |
      "Dagger cache service token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install CLI"
      id: "install-cli"
      shell: "sh"
      env:
        DAGGER_VERSION: "${{ inputs.version }}"
      run: |
        cd '/usr/local'
        curl -L 'https://dl.dagger.io/dagger/install.sh' | sudo -E sh

    - name: "Start engine"
      id: "start-engine"
      shell: "sh"
      run: |
        docker run \
          --name 'dagger-engine' \
          --detach \
          --stop-signal 'SIGTERM' \
          --privileged \
          --volume 'dagger-engine:/var/lib/dagger' \
          --env '_EXPERIMENTAL_DAGGER_SERVICES_DNS' \
          --env '_EXPERIMENTAL_DAGGER_CACHESERVICE_URL=${{ inputs.cacheServiceURL }}' \
          --env '_EXPERIMENTAL_DAGGER_CACHESERVICE_TOKEN=${{ inputs.cacheServiceToken }}' \
          'registry.dagger.io/engine:v${{ inputs.version }}'

        echo '_EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://dagger-engine' >> "$GITHUB_ENV"
        echo '_EXPERIMENTAL_DAGGER_CLOUD_TOKEN=${{ inputs.cloudToken }}' >> "$GITHUB_ENV"
