FROM docker.io/curlimages/curl:7.86.0 as downloader
ARG varnish_exporter_version="1.6.1"

RUN set -x \
 && cd /tmp \
 && curl -L https://github.com/jonnenauha/prometheus_varnish_exporter/releases/download/$varnish_exporter_version/prometheus_varnish_exporter-$varnish_exporter_version.linux-amd64.tar.gz --output prometheus_varnish_exporter.tar.gz \
 && tar -xzf prometheus_varnish_exporter.tar.gz \
 && mv prometheus_varnish_exporter-$varnish_exporter_version.linux-amd64/prometheus_varnish_exporter .

# /!\ KEEP THE BASE IMAGE IN SYNC ACROSS ALL DOCKERFILES /!\
FROM docker.io/varnish:7.2.0

COPY --from=downloader /tmp/prometheus_varnish_exporter /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/prometheus_varnish_exporter" ]
