FROM golang:1.14.10 as downloader
ARG varnish_exporter_version="1.6.1"

RUN set -x \
 && cd src \
 && curl -L https://github.com/jonnenauha/prometheus_varnish_exporter/releases/download/$varnish_exporter_version/prometheus_varnish_exporter-$varnish_exporter_version.linux-amd64.tar.gz --output prometheus_varnish_exporter.tar.gz \
 && tar -xzf prometheus_varnish_exporter.tar.gz \
 && mv prometheus_varnish_exporter-$varnish_exporter_version.linux-amd64/prometheus_varnish_exporter .

# /!\ KEEP THE BASE IMAGE IN SYNC ACROSS ALL DOCKERFILES /!\
FROM varnish:7.1.1

COPY --from=downloader /go/src/prometheus_varnish_exporter /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/prometheus_varnish_exporter" ]
