---
name: "Post Setup Dagger"
description: "Post Setup Dagger"
runs:
  using: "composite"
  steps:
    - name: "Stop engine"
      id: "stop-engine"
      shell: "sh"
      run: |
        docker stop --time 60 'dagger-engine'
        docker logs 'dagger-engine'
